### ISSUE TITLE
Identify and create your font styles.

### ISSUE THREAD

**Issue by robcapell** [robcapell/maxnixon-practice-shoe_mockup#2]
Websites always have consistency from page to page. One of the places you will ALWAYS see consistency, from page to page on a website, is its font styles.
Look at each mock, and find the consistencies in font styles from page to page.
Create these styles for later use when you are working on each mockup.
Please comment for any questions. Move on to another ticket until you have the info you need.

**Comment by maxnixon** [comment]
Could you please help me identify the font sizes and styles the seperate pages should have?
How am I supposed to know if the pictures text lives in which tag? EX: h1, h2, p etc.
Or is that a personal preference sort of info?

**Comment by robcapell** [comment]
Use this font site wide - https://fonts.google.com/specimen/Poppins
And create variations of classes to handle the different styles you see in the mocks like we talked about. Smallest font size should be 14px, medium font size should be 18px, large should be 32px.
Use those sizes, with the colors and font weights in the mocksups to create your global font style classes.
