### ISSUE TITLE
Create footer styles and element.

### ISSUE THREAD

**Issue by robcapell** [robcapell/maxnixon-practice-shoe_mockup#4]
Just like the font styles and header, the footer on websites, from page to page, is general the same. Develop the footer styles and footer element (including child elements.)

**Comment by maxnixon** [comment]
I'm a little stuck on inputting the code for the email adress bar for users to sign up for promotions.... any suggestions
![footer](https://user-images.githubusercontent.com/25624899/27453301-f70dc140-5763-11e7-8e70-c687651ea38d.jpg)
